version: "3"

tasks:
  build:
    dir: src-tauri/db
    cmd: cargo run --bin show_pokemons
  runmig:
    dir: src-tauri/db
    cmd: diesel migration run
  revmig:
    dir: src-tauri/db
    cmd: diesel migration revert
