version: "3"

tasks:
  test:
    dir: "{{ .tests }}"
    cmd: cargo test -- --no-capture
  docs:
    env:
      RUSTDOCFLAGS: --cfg docsrs
    dir: "{{ .protocheck }}"
    cmd: cargo +nightly doc --all-features --open
