#![cfg_attr(docsrs, feature(doc_auto_cfg))]

//! This crate contains the core logic used by the code generated by [`protocheck-proc-macro`](protocheck-proc-macro).
//! You do not need to use this crate directly. Refer to [`protocheck`](protocheck) to learn more about how to set up automatic validators generation for structs generated from protobuf definitions.

pub(crate) use proto_types::{field_descriptor_proto::Type as ProtoType, protovalidate};

/// The context about the field being validated that is passed to the validators.
pub mod field_data;

/// The functions executing the validation logic. These are called by the validators added by [protocheck-proc-macro] to the target structs.
pub mod validators;
