[package]
name = "macro_impl"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
prost = { workspace = true }
serde = { workspace = true }
pr_macro = { path = "../pr_macro/" }
proto_types = { path = "../proto_types/" }

[build-dependencies]
prost-build = { workspace = true }
