[package]
name = "macro_impl"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
prost = "0.14.1"
serde = { version = "1", features = ["derive"] }
pr_macro = { path = "../pr_macro/" }
proto_types = { path = "../proto_types/" }

[build-dependencies]
prost-build = "0.14.1"
