[package]
name = "builder"
publish = false
license.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
prost-build = { workspace = true }
