[package]
name = "pr_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
prost = { workspace = true }
serde = { workspace = true }
prost-reflect = { workspace = true }
cel-interpreter = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
bytes = { workspace = true }
regex = { workspace = true }
proto_types = { path = "../proto_types/" }

[build-dependencies]
prost-build = { workspace = true }
